=== tiantiandouhao/Shop123_CE/lib/internal/Magento/Framework/Config/etc/view.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="view">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="vars" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="var" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="module" type="xs:string" use="required"/>
                    </xs:complexType>
                    <xs:unique name="varNameIdentifier">
                        <xs:selector xpath="var"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="exclude" minOccurs="0" maxOccurs="1" type="excludeType"/>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="varsModuleIdentifier">
            <xs:selector xpath="vars"/>
            <xs:field xpath="@module"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="excludeType">
        <xs:sequence>
            <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="itemType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="file"/>
                            <xs:enumeration value="directory"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== tiantiandouhao/Shop123_CE/app/design/frontend/Magento/blank/etc/view.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/Config/etc/view.xsd">
    <vars module="Magento_Catalog">
        <var name="product_small_image_sidebar_size">100</var>  <!-- Override for small product image -->
        <var name="product_base_image_size">275</var>           <!-- Override for base product image -->
        <var name="product_base_image_icon_size">48</var>       <!-- Base product image icon size -->

        <var name="product_list_image_size">166</var>           <!-- New Product image size used in product list -->
        <var name="product_zoom_image_size">370</var>           <!-- New Product image size used for zooming -->

        <var name="product_image_white_borders">0</var>

        <var name="review_page_product_image:type">small_image</var>
        <var name="review_page_product_image:width">285</var>
        <var name="review_page_product_image:ratio">1</var>
        <var name="review_page_product_image:height">285</var>

        <var name="customer_account_product_review_page:type">image</var>
        <var name="customer_account_product_review_page:width">285</var>
        <var name="customer_account_product_review_page:ratio">1</var>
        <var name="customer_account_product_review_page:height">285</var>

        <var name="category_page_list:type">small_image</var>
        <var name="category_page_list:width">240</var>
        <var name="category_page_list:ratio">1</var>
        <var name="category_page_list:height">300</var>

        <var name="category_page_grid:type">small_image</var>
        <var name="category_page_grid:width">240</var>
        <var name="category_page_grid:ratio">1</var>
        <var name="category_page_grid:height">300</var>

        <var name="product_comparison_list:type">small_image</var>
        <var name="product_comparison_list:width">140</var>
        <var name="product_comparison_list:ratio">1</var>
        <var name="product_comparison_list:height">140</var>

        <var name="related_products_list:type">small_image</var>
        <var name="related_products_list:width">140</var>
        <var name="related_products_list:ratio">1</var>
        <var name="related_products_list:height">140</var>

        <var name="upsell_products_list:type">small_image</var>
        <var name="upsell_products_list:width">140</var>
        <var name="upsell_products_list:ratio">1</var>
        <var name="upsell_products_list:height">140</var>

        <var name="product_page_main_image:type">image</var>
        <var name="product_page_main_image:width">700</var>
        <var name="product_page_main_image:ratio">1</var>
        <var name="product_page_main_image:height">700</var>

        <var name="product_page_main_image_default:type">image</var>
        <var name="product_page_main_image_default:width">700</var>
        <var name="product_page_main_image_default:ratio">1</var>
        <var name="product_page_main_image_default:height">700</var>

        <var name="product_page_more_views:type">thumbnail</var>
        <var name="product_page_more_views:width">90</var>
        <var name="product_page_more_views:ratio">1</var>
        <var name="product_page_more_views:height">90</var>

        <var name="side_column_widget_product_thumbnail:type">thumbnail</var>
        <var name="side_column_widget_product_thumbnail:width">75</var>
        <var name="side_column_widget_product_thumbnail:ratio">0.8</var>
        <var name="side_column_widget_product_thumbnail:height">90</var>

        <var name="new_products_content_widget_list:type">small_image</var>
        <var name="new_products_content_widget_list:width">270</var>
        <var name="new_products_content_widget_list:ratio">1</var>
        <var name="new_products_content_widget_list:height">270</var>

        <var name="new_products_content_widget_grid:type">small_image</var>
        <var name="new_products_content_widget_grid:width">240</var>
        <var name="new_products_content_widget_grid:ratio">1</var>
        <var name="new_products_content_widget_grid:height">300</var>

        <var name="recently_compared_products_images_names_widget:type">thumbnail</var>
        <var name="recently_compared_products_images_names_widget:width">75</var>
        <var name="recently_compared_products_images_names_widget:ratio">0.8</var>
        <var name="recently_compared_products_images_names_widget:height">90</var>

        <var name="recently_viewed_products_images_names_widget:type">small_image</var>
        <var name="recently_viewed_products_images_names_widget:width">75</var>
        <var name="recently_viewed_products_images_names_widget:ratio">0.8</var>
        <var name="recently_viewed_products_images_names_widget:height">90</var>

        <var name="recently_compared_products_images_only_widget:type">thumbnail</var>
        <var name="recently_compared_products_images_only_widget:width">76</var>
        <var name="recently_compared_products_images_only_widget:ratio">1</var>
        <var name="recently_compared_products_images_only_widget:height">76</var>

        <var name="recently_viewed_products_images_only_widget:type">small_image</var>
        <var name="recently_viewed_products_images_only_widget:width">76</var>
        <var name="recently_viewed_products_images_only_widget:ratio">1</var>
        <var name="recently_viewed_products_images_only_widget:height">76</var>

        <var name="bundled_product_customization_page:type">thumbnail</var>
        <var name="bundled_product_customization_page:width">140</var>
        <var name="bundled_product_customization_page:ratio">1</var>
        <var name="bundled_product_customization_page:height">140</var>

        <var name="recently_compared_products_grid_content_widget:type">small_image</var>
        <var name="recently_compared_products_grid_content_widget:width">240</var>
        <var name="recently_compared_products_grid_content_widget:ratio">1</var>
        <var name="recently_compared_products_grid_content_widget:height">300</var>

        <var name="recently_compared_products_list_content_widget:type">small_image</var>
        <var name="recently_compared_products_list_content_widget:width">270</var>
        <var name="recently_compared_products_list_content_widget:ratio">1</var>
        <var name="recently_compared_products_list_content_widget:height">207</var>

        <var name="recently_viewed_products_grid_content_widget:type">small_image</var>
        <var name="recently_viewed_products_grid_content_widget:width">240</var>
        <var name="recently_viewed_products_grid_content_widget:ratio">1</var>
        <var name="recently_viewed_products_grid_content_widget:height">300</var>

        <var name="recently_viewed_products_list_content_widget:type">small_image</var>
        <var name="recently_viewed_products_list_content_widget:width">270</var>
        <var name="recently_viewed_products_list_content_widget:ratio">1</var>
        <var name="recently_viewed_products_list_content_widget:height">270</var>

        <var name="customer_shared_wishlist:type">small_image</var>
        <var name="customer_shared_wishlist:width">113</var>
        <var name="customer_shared_wishlist:ratio">1</var>
        <var name="customer_shared_wishlist:height">113</var>

        <var name="wishlist_thumbnail:type">small_image</var>
        <var name="wishlist_thumbnail:width">240</var>
        <var name="wishlist_thumbnail:ratio">1</var>
        <var name="wishlist_thumbnail:height">300</var>

        <var name="wishlist_sidebar_block:type">thumbnail</var>
        <var name="wishlist_sidebar_block:width">75</var>
        <var name="wishlist_sidebar_block:ratio">0.8</var>
        <var name="wishlist_sidebar_block:height">90</var>

        <var name="shared_wishlist_email:type">small_image</var>
        <var name="shared_wishlist_email:width">135</var>
        <var name="shared_wishlist_email:ratio">1</var>
        <var name="shared_wishlist_email:height">135</var>

        <var name="customer_account_my_tags_tag_view:type">small_image</var>
        <var name="customer_account_my_tags_tag_view:width">100</var>
        <var name="customer_account_my_tags_tag_view:ratio">1</var>
        <var name="customer_account_my_tags_tag_view:height">100</var>

        <var name="cart_cross_sell_products:type">thumbnail</var>
        <var name="cart_cross_sell_products:width">152</var>
        <var name="cart_cross_sell_products:ratio">1</var>
        <var name="cart_cross_sell_products:height">188</var>

        <var name="gift_messages_checkout_thumbnail:type">thumbnail</var>
        <var name="gift_messages_checkout_thumbnail:width">100</var>
        <var name="gift_messages_checkout_thumbnail:ratio">1</var>
        <var name="gift_messages_checkout_thumbnail:height">100</var>

        <var name="gift_messages_checkout_small_image:type">small_image</var>
        <var name="gift_messages_checkout_small_image:width">75</var>
        <var name="gift_messages_checkout_small_image:ratio">1</var>
        <var name="gift_messages_checkout_small_image:height">75</var>

        <var name="mini_cart_product_thumbnail:type">thumbnail</var>
        <var name="mini_cart_product_thumbnail:width">78</var>
        <var name="mini_cart_product_thumbnail:ratio">1</var>
        <var name="mini_cart_product_thumbnail:height">78</var>

        <var name="new_products_images_only_widget:type">small_image</var>
        <var name="new_products_images_only_widget:width">78</var>
        <var name="new_products_images_only_widget:ratio">1</var>
        <var name="new_products_images_only_widget:height">78</var>

        <var name="cart_page_product_thumbnail:type">small_image</var>
        <var name="cart_page_product_thumbnail:width">110</var>
